### ISSUE TITLE
[Feature]: Improve project readme

### ISSUE THREAD

**Issue by aliabbasjaffri** [mlinfra-io/mlinfra#100]
### Describe the Feature

The project readme has been outdated for a while and needs some updating.

### Importance of the Feature

Would be nice to get project readme get updated

### Feature Category

Documentation

**Comment by M-DEV-1** [comment]
Hi, I would like to work on this issue. Could you specify your expectations for the improvement?

**Comment by aliabbasjaffri** [comment]
hey @M-DEV-1 i reserved this issue for myself to update the project readme. You are most welcome to pick any other.
