### ISSUE TITLE
[Feature]: Add rich to mlinfra cli to allow better understanding of stacktrace

### ISSUE THREAD

**Issue by aliabbasjaffri** [mlinfra-io/mlinfra#96]
### Describe the Feature

[rich library](https://github.com/Textualize/rich) allows better terminal output. Rich can also render pretty tracebacks in case code runs into an exception

### Importance of the Feature

This improves the stacktrace reading capability of the code and allows users to understand the errors better.

### Feature Category

mlinfra cli

**Comment by ara-25** [comment]
Hi, I am interested in working on this as part of hacktoberfest. Is it possible to assign it to me?
Thanks,

**Comment by aliabbasjaffri** [comment]
Hey @ara-25! Certainly, all the best and do let me know if you have any further questions :-)
