### ISSUE TITLE
[Feature]: Replace cli from pyinvoke to typer

### ISSUE THREAD

**Issue by aliabbasjaffri** [mlinfra-io/mlinfra#99]
### Describe the Feature

mlinfra cli currently uses [pyinvoke](https://www.pyinvoke.org/) to allow interaction via cli. However we would like to replace it with [typer](https://typer.tiangolo.com/) due it its better features and maintenance.

### Importance of the Feature

Currently we're using pyinvoke under the hood, to allow users interact with mlinfra cli. However this has proven to be bit clunky over the time and its rather difficult to customize it, whereas [typer by tiangolo](https://github.com/tiangolo) is an absolute joy to use and we would like to provide our users with the joyful interface of interacting with mlinfra cli.

### Feature Category

mlinfra cli

**Comment by Spiritedswordsman** [comment]
Heyy, Im interested to work on this issue, can you please assign me?
